### ISSUE TITLE
Failed to start: invalid interaction specified

### ISSUE THREAD

**Issue by acuntex** [sensepost/objection#51] opened 2018-01-31 16:01 UTC
After injecting Frida with objection to an apk, the app runs, but apparently I cannot connect.

adb logcat showed the following errors:
```
01-31 16:54:00.357 29877 29877 F GLib    : g_path_get_basename: assertion 'file_name != NULL' failed
01-31 16:54:00.357 29877 29877 F Frida   : frida_gadget_location_construct: assertion 'executable_name != NULL' failed
01-31 16:54:00.357 29877 29877 F Frida   : frida_gadget_load_config: assertion 'location != NULL' failed
01-31 16:54:00.357 29877 29877 F Frida   : frida_gadget_config_get_code_signing: assertion 'self != NULL' failed
01-31 16:54:00.357 29877 29877 F Frida   : frida_gadget_location_get_range: assertion 'self != NULL' failed
01-31 16:54:00.357 29877 29877 F Frida   : frida_gadget_config_get_interaction: assertion 'self != NULL' failed
01-31 16:54:00.357 29877 29877 F Frida   : frida_gadget_config_get_runtime: assertion 'self != NULL' failed
01-31 16:54:00.359 29877 29938 F Frida   : frida_gadget_config_get_interaction: assertion 'self != NULL' failed
01-31 16:54:00.359 29877 29938 F Frida   : Failed to start: invalid interaction specified
```

Packaging OS is Windows 10.
Smartphone is Galaxy S8 with Oreo.

**Comment by leonjza** [comment] 2018-01-31 16:08
This looks like it could be a Frida specific problem.

**Comment by leonjza** [comment] 2018-01-31 16:14
Confirmed via Telegram. Should be fixed soon (if not in the next version of Frida already).

**Comment by acuntex** [comment] 2018-01-31 16:15
Great, thank you! 💯 👍

**Comment by acuntex** [comment] 2018-01-31 18:22
As a workaround: Is it possible to use an older version of the frida gadget?
It's always getting "Github FridaGadget v10.6.44"

**Comment by leonjza** [comment] 2018-01-31 18:32
Absolutely. It is a manual workaround for now, but is doable. I hope to add the `--gadget-version` flag soon :). For now, the following should let you use older gadgets:

- Browse to the Frida releases page here: https://github.com/frida/frida/releases
- Choose the version you want to try, and download the appropriate `frida-gadget` for your architecture. For example: `frida-gadget-10.6.43-android-arm64.so.xz` for v10.6.43 of the arm64 gadget.
- Extract the gadget with `unxz gadget-name.so.xz`
- Override the `libfrida-gadget.so` file located in the `~/.objection/android/<architecture>/` directory with the one you downloaded.
- Patch the APK with objection.

Doing this objection will still report the gadget as the latest version (it is read from `~/.objection/gadget_versions`) but will use the physical file you replaced it with. The next time there is a Frida update though, your replaced gadget will be updated to the latest, so you will have to repeat to get the older one again.

HTH (and yes, I would love to improve this)!

**Comment by acuntex** [comment] 2018-01-31 18:40
Awesome! Works perfect with 10.6.43. :)

**Comment by acuntex** [comment] 2018-01-31 19:21
btw.: If you somehow implement `--gadget-version`, there is currently another bug related to the github check:

> Github FridaGadget is v10.6.45, local is v10.6.44. Updating...
> Unable to determine URL to download the library

Apparently there is a new frida version, but the arm64-version hasn't been uploaded yet.

**Comment by leonjza** [comment] 2018-01-31 19:24
Indeed, new Frida versions take a while to upload from the Frida build server. Just give it a bit.

**Comment by leonjza** [comment] 2018-02-13 08:16
I think this is fixed in the latest Frida gadget, but there is also the `--gadget-version` flag introduced in objection v1.2.4 to help when this happens in the future.

**Closed by leonjza** 2018-02-13 08:16 UTC
Labels: bug, frida
