### ISSUE TITLE
Disable Root Detection before the application start

### ISSUE THREAD

**Issue by flamecopper** [sensepost/objection#470] opened 2021-07-20 09:34 UTC
android root disable
ios jailbreak disable

Normally for these command, it will run after the application is started.
Is there any way to do this before the application starts?

**Comment by leonjza** [comment] 2021-07-20 10:33
The best option now is to use it as a startup command. Hopefully when I finally get to the spawn logic refactoring I'll try and improve the early instrumentation.

Marking this as a duplicate of #335

**Closed by leonjza** 2021-07-20 10:33 UTC
Labels: ✨enhancement
