### ISSUE TITLE
[bug] Cannot install patched split apk (apks)

### ISSUE THREAD

**Issue by rypz79** [sensepost/objection#425] opened 2020-11-18 15:30 UTC
**Describe the bug**
Following [this](https://github.com/sensepost/objection/wiki/Patching-Android-Applications#optional---obtaining-play-store-apks) tutorial, I got a split apk
```
roey@HP-Spectre-x360-13:~/ApkProjects$ adb shell pm path com.goldtouch.ynet
package:/data/app/com.goldtouch.ynet-qbwggjZ6lz65HoS35SuAGw==/base.apk
package:/data/app/com.goldtouch.ynet-qbwggjZ6lz65HoS35SuAGw==/split_config.arm64_v8a.apk
package:/data/app/com.goldtouch.ynet-qbwggjZ6lz65HoS35SuAGw==/split_config.en.apk
package:/data/app/com.goldtouch.ynet-qbwggjZ6lz65HoS35SuAGw==/split_config.xxhdpi.apk
```
So I decided to get an apks using LuckyPatcher backup, then using AntiSplit merge it (.apks->.apk)
Then patch the apk:
```
roey@HP-Spectre-x360-13:~/ApkProjects$ objection patchapk --source ynet_v6.79-b162.apk 
No architecture specified. Determining it using `adb`...
Detected target device architecture as: arm64-v8a
Using latest Github gadget version: 14.0.8
Patcher will be using Gadget version: 14.0.8
Detected apktool version as: 2.4.1
Running apktool empty-framework-dir...
I: Removing 1.apk framework file...
Unpacking ynet_v6.79-b162.apk
App already has android.permission.INTERNET
Setting extractNativeLibs to true...
Target class not specified, searching for launchable activity instead...
Reading smali from: /tmp/tmpoexmxfqf.apktemp/smali/com/goldtouch/ynet/ui/activities/SplashActivity.smali
Injecting loadLibrary call at line: 47
Attempting to fix the constructors .locals count
Current locals value is 0, updating to 1:
Writing patched smali back to: /tmp/tmpoexmxfqf.apktemp/smali/com/goldtouch/ynet/ui/activities/SplashActivity.smali
Copying Frida gadget to libs path...
Rebuilding the APK with the frida-gadget loaded...
Built new APK with injected loadLibrary and frida-gadget
Signing new APK.
Signed the new APK
Performing zipalign
Zipalign completed
Copying final apk from /tmp/tmpoexmxfqf.apktemp.aligned.objection.apk to ynet_v6.79-b162.objection.apk in current directory...
Cleaning up temp files...
```
Moved it to the my rooted android device -> installed the apk -> run it...it hangs (Tried cleaning DATA)
**When I opened playstore I noticed that he wants to upgrade the app**

**Expected behavior**
The patched app should be running in my android device

**Environment (please complete the following information):**
- Host: Kubuntu 20.10 , Linux v5.8.0-25-generic x64 
- Device: SM-N975 (Samsung N10+) ROOTED
 - OS: Android 10
 - Frida Version: 12.11.17
- Objection Version: 1.9.6

**Application**
Ynet Newspaper
[ynet_v6.79-b162.objection.zip](https://github.com/sensepost/objection/files/5561011/ynet_v6.79-b162.objection.zip)

**Comment by leonjza** [comment] 2020-11-19 07:43
Duplicate of #358. Check out https://github.com/NickstaDB/patch-apk to help with the patching process.

**Closed by leonjza** 2020-11-19 07:43 UTC
Labels: duplicate
