### ISSUE TITLE
Parenthesis on APK name make apktool crash

### ISSUE THREAD

**Issue by esauvisky** [sensepost/objection#289] opened 2019-10-25 17:12 UTC
**Describe the bug**
When patching an APK with frida-gadget, if the APK filename contains any parenthesis, the whole process fails.

**To Reproduce**
1. Rename any APK and add a `(` parenthesis.
2. Run `objection patchapk --source [apk-(with)-parenthesis.apk`

**Expected behavior**
The APK gets properly patched.

**Evidence / Logs / Screenshots**
Any output from objection, such as stack traces or errors that occurred. Be sure to run objection with the `--debug` flag so that errors from the agent are verbose enough to debug. For example:

```text
Unpacking com.nianticlabs.pokemongo_0.159.0-2019101800_minAPI21(armeabi-v7a)(nodpi)_apkmirror.com.apk
An error may have occurred while extracting the APK.
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `/usr/bin/apktool decode -f "" -o /tmp/tmpbzcyos0p.apktemp com.nianticlabs.pokemongo_0.159.0-2019101800_minAPI21(armeabi-v7a)(nodpi)_apkmirror.com.apk'

An error may have occurred while running aapt.
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `/opt/android-sdk/build-tools/29.0.2/aapt dump badging com.nianticlabs.pokemongo_0.159.0-2019101800_minAPI21(armeabi-v7a)(nodpi)_apkmirror.com.apk'

Traceback (most recent call last):
  File "/usr/bin/objection", line 11, in <module>
    load_entry_point('objection==1.6.4', 'console_scripts', 'objection')()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/objection/console/cli.py", line 342, in patchapk
    patch_android_apk(**locals())
  File "/usr/lib/python3.7/site-packages/objection/commands/mobile_packages.py", line 153, in patch_android_apk
    patcher.inject_internet_permission(skip_resources=skip_resources)
  File "/usr/lib/python3.7/site-packages/objection/utils/patchers/android.py", line 389, in inject_internet_permission
    xml = self._get_android_manifest()
  File "/usr/lib/python3.7/site-packages/objection/utils/patchers/android.py", line 239, in _get_android_manifest
    return ElementTree.parse(os.path.join(self.apk_temp_directory, 'AndroidManifest.xml'))
  File "/usr/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpbzcyos0p.apktemp/AndroidManifest.xml'
Cleaning up temp files...
Failed to cleanup with error: [Errno 2] No such file or directory: '/tmp/tmpbzcyos0p.apktemp.objection.apk'

```

**Environment (please complete the following information):**
- Device: [e.g. Redmi Note 5]
- OS: [e.g. Android 8]
- Frida Version [e.g. 12.7.12]
- Objection Version [e.g. 1.6.4]

Renaming the file downloaded from apkmirror to something simple like 'app.apk' solves the problem.

**Comment by leonjza** [comment] 2019-10-25 17:23
Duplicate of #234. Fixed since version 1.7.2. Please upgrade to the latest release.

**Closed by leonjza** 2019-10-25 17:23 UTC
Labels: duplicate
