### ISSUE TITLE
aapt and apktool problem - cant patch

### ISSUE THREAD

**Issue by Rick11929** [sensepost/objection#257] opened 2019-07-19 09:53 UTC
Hello,
I can't patch apk.

I receive such error while running "objection patchapk --source target.apk":

`
Detected target device architecture as: arm64-v8a
Using latest Github gadget version: 12.6.11
Patcher will be using Gadget version: 12.6.11
Unpacking target.apk
An error may have occurred while extracting the APK.
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `/usr/local/bin/apktool decode -f "" -o /tmp/tmpvsu7gszi.apktemp target.apk'

An error may have occurred while running aapt.
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `/Users/isr/Library/Android/sdk/build-tools/28.0.3/aapt dump badging target.apk'
`
Any idea about that ?

**Comment by aph3rson** [comment] 2019-08-02 21:46
Is the name of your package `target.apk`, or does it contain a space/special characters? This may be related to #234.

**Comment by leonjza** [comment] 2019-08-14 12:41
This is a duplicate of #234 as @aph3rson mentioned. Rename the APK to not have any special characters or spaces. Should be fixed soon though.

**Closed by leonjza** 2019-08-14 12:41 UTC
Labels: duplicate
