### ISSUE TITLE
jarsigner: unable to sign jar: java.util.zip.ZipException: duplicate entry: META-INF/services/kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader

### ISSUE THREAD

**Issue by guillaumelh** [sensepost/objection#328] opened 2020-02-27 19:59 UTC
Hi, I'm getting the following error : 

> jarsigner: unable to sign jar: java.util.zip.ZipException: duplicate entry: META-INF/services/kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader

While executing this command : 

> sudo objection patchapk --source foo.apk --skip-resources --use-aapt2 --gadget-version 12.8.11

OS X, device is an Android and I managed to temper and install other apps before with the same Mac and same device.

Here is the full log and traceback :

```Detected target device architecture as: arm64-v8a
Using manually specified version: 12.8.11
Patcher will be using Gadget version: 12.8.11
Unpacking coup.apk
App already has android.permission.INTERNET
Target class not specified, searching for launchable activity instead...
Smali not found in smali directory. This might be a multidex APK. Searching...
Found smali at: /tmp/tmpbixfmkyp.apktemp/smali_classes2/com/joincoup/app/ui/splash/SplashActivity.smali
Reading smali from: /tmp/tmpbixfmkyp.apktemp/smali_classes2/com/joincoup/app/ui/splash/SplashActivity.smali
Injecting into an existing constructor
Injecting loadLibrary call at line: 85
Attempting to fix the constructors .locals count
Current locals value is 2, updating to 3:
Writing patched smali back to: /tmp/tmpbixfmkyp.apktemp/smali_classes2/com/joincoup/app/ui/splash/SplashActivity.smali
Copying Frida gadget to libs path...
Rebuilding the APK with the frida-gadget loaded...
Appending 73 extra entries in META-INF to the APK...
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/zipfile.py:1515: UserWarning: Duplicate name: 'META-INF/services/kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader'
  return self._open_to_write(zinfo, force_zip64=force_zip64)
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/zipfile.py:1515: UserWarning: Duplicate name: 'META-INF/services/kotlin.reflect.jvm.internal.impl.resolve.ExternalOverridabilityCondition'
  return self._open_to_write(zinfo, force_zip64=force_zip64)
Built new APK with injected loadLibrary and frida-gadget
Signing new APK.
Signing the new APK may have failed.
jarsigner: unable to sign jar: java.util.zip.ZipException: duplicate entry: META-INF/services/kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader ```

**Comment by leonjza** [comment] 2020-02-28 08:06
Duplicate of #319.

**Closed by leonjza** 2020-02-28 08:06 UTC
Labels: duplicate
