### ISSUE TITLE
Patching an IPA

### ISSUE THREAD

**Issue by jtoldt** [sensepost/objection#7] opened 2017-08-06 12:27 UTC
Getting an error when trying to patch an IPA, I double checked all the dependencies and they looked good.  

![image](https://user-images.githubusercontent.com/29126626/29003184-8de8e2c6-7a77-11e7-8dc2-955de3260082.png)

Not sure if it's an issue with my IPA file or something isn't installed/configured right.

**Comment by leonjza** [comment] 2017-08-07 07:52
At first glance, it looks like objection had trouble parsing a `.mobileprovision` file that you had on disk. When patching, it searches for provisioning profiles in `~/Library/Developer/Xcode/DerivedData/` [in version 0.1.1](https://github.com/sensepost/objection/blob/0.1.1/objection/commands/mobile_packages.py#L129-L130) if the location of one is not specified.

Assuming you have deployed a blank iOS project from XCode to get a provisioning file generated, would it be possible to check if you can manually read this file with the following steps?

- `cd` to `~/Library/Developer/Xcode/DerivedData`
- Locate the `embedded.mobileprovision` file with: `find . | grep "embedded.mobileprovision"`
- Take note of the path, and run `security cms -D -i <path to profile>`

The output of the above steps should be a clear text XML file containing all of the information about the provisioning profile. Could you confirm that this is the case?

**Comment by jtoldt** [comment] 2017-08-10 03:14
Yes, following those steps produced an XML file containing all of the information about the provisioning profile.

**Comment by leonjza** [comment] 2017-08-10 07:14
Could you try running the `objection patchipa` command with the `-p` flag, specifying the `. mobileprovision` file to use instead of having objection search for one for you?

**Comment by jtoldt** [comment] 2017-08-18 21:49
I reinstalled the dependencies and it's now finding a valid provisioning profile, however it looks like I'm still getting similar errors.  I haven't had a chance to troubleshoot much further yet.

<img width="885" alt="objection" src="https://user-images.githubusercontent.com/29126626/29478918-1c117646-8435-11e7-82e1-78276069b2fe.png">

**Comment by leonjza** [comment] 2017-08-19 07:17
Thanks for following up! It looks like the `Payload` directory expected when extracting the `.ipa` does not exist for some reason. Is this `ctm.ipa` application one that you can share with me?

**Comment by leonjza** [comment] 2017-09-22 06:30
Closing for now. Feel free to reopen if you have some more information / steps to reproduce.

**Closed by leonjza** 2017-09-22 06:30 UTC
Labels: bug
