### ISSUE TITLE
Exceptions when Objection is run

### ISSUE THREAD

**Issue by encryptedsin** [sensepost/objection#181] opened 2019-02-05 10:52 UTC
I am having an issue with objection.
Specs:
Python 3.7.2 and Python 2.7.13 installed.
Frida 12.3.1 installed along with frida-tools.
OS: Windows 10

The below exception is thrown when i attempt to run objection (even in powershell):
PS C:\Users\JYOTIS> objection
Traceback (most recent call last):
File "c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources__init__.py", line 581, in _build_master ws.require(**requires**) File "c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources__init__.py", line 898, in require
needed = self.resolve(parse_requirements(requirements))
File "c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources__init__.py", line 789, in resolve
raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (prompt-toolkit 2.0.8 (c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages), Requirement.parse('prompt_toolkit<2.0.0,>=1.0.15'), {'objection'})

During handling of the above exception, another exception occurred:
PS C:\Users{USER}> objection
Traceback (most recent call last):
File "C:\Users\JYOTIS\AppData\Local\Programs\Python\Python37-32\Scripts\objection-script.py", line 6, in 
from pkg_resources import load_entry_point
File "c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources__init__.py", line 3126, in 
@_call_aside File "c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources__init__.py", line 3110, in _call_aside f(*args, **kwargs) File "c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources__init__.py", line 3139, in _initialize_master_working_set
working_set = WorkingSet._build_master() File "c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources__init__.py", line 583, in _build_master
return cls._build_from_requirements(**requires**) File "c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources__init__.py", line 596, in _build_from_requirements dists = ws.resolve(reqs, Environment()) File "c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources__init__.py", line 784, in resolve
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'prompt_toolkit<2.0.0,>=1.0.15' distribution was not found and is required by objection.

If I uninstall objection, frida-ps too throws the exception caused by missing prompt_toolkit<2.0.0,>=1.0.15.

Below is fro extra reference:
PS C:\Users\JYOTIS> pip3 install prompt_toolkit
Requirement already satisfied: prompt_toolkit in c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages (2.0.8)
Requirement already satisfied: six>=1.9.0 in c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages (from prompt_toolkit) (1.12.0)
Requirement already satisfied: wcwidth in c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages (from prompt_toolkit) (0.1.7)

Kindly assist.

**Comment by mpgn** [comment] 2019-02-05 10:59
Duplicate of #179

**Comment by leonjza** [comment] 2019-02-05 15:24
Yeah, dupe of #179.

**Closed by leonjza** 2019-02-05 15:24 UTC
Labels: duplicate
