### ISSUE TITLE
Keychain dump fails on iOS 12 device with or without jailbreak

### ISSUE THREAD

**Issue by commjoen** [sensepost/objection#238] opened 2019-06-06 13:13 UTC
**Describe the bug**
When we patch DVIA-V2 app objection and  we deploy it to a iOS 12.0 (jailbroken or not), and try to dump the keychain, it fails to decode the data and some of the accountnames.

**To Reproduce**
1. patch the IPA `objection patchipa -c <codesignid> -s DVIA-v2-swift.ipa -p  embedded.mobileprovision`
2.  unzip the ipa `unzip DVIA-v2-swift-frida-codesigned.ipa` 
3.  deploy the ipa  `ios-deploy --bundle Payload/DVIA-v2.app -d -v `
4. start the repl `objection  --gadget DVIA-V2 explore`
5. execute the keychain dump: `ios keychain dump `

**Expected behavior**
it should provide an overview of all the values in the keychain for the given app without any "failed to decode" entries.

**Evidence / Logs / Screenshots**
Any output from objection, such as stack traces or errors that occurred. Be sure to run objection with the `--debug` flag so that errors from the agent are verbose enough to debug. For example:

```text
objection  --gadget DVIA-V2 explore
Using USB device `iPad 4`
Agent injected and responds ok!

     _     _         _   _
 ___| |_  |_|___ ___| |_|_|___ ___
| . | . | | | -_|  _|  _| | . |   |
|___|___|_| |___|___|_| |_|___|_|_|
        |___|(object)inject(ion) v1.6.4

     Runtime Mobile Exploration
        by: @leonjza from @sensepost

[tab] for command suggestions
....highaltitudehacks.DVIAswiftv2 on (iPad: 12.0) [usb] # ios keychain dump                                                                                                                
Note: You may be asked to authenticate using the devices passcode or TouchID
Save the output by adding `--json keychain.json` to this command
Dumping the iOS keychain...
Created                    Accessible            ACL    Type      Account             Service                                                Data
-------------------------  --------------------  -----  --------  ------------------  -----------------------------------------------------  ------------------
2019-06-05 19:36:51 +0000  WhenUnlocked          None   Password  (failed to decode)  com.highaltitudehacks.DVIAswiftv2com.flurry.analytics  (failed to decode)
2019-06-05 19:36:51 +0000  WhenUnlocked          None   Password  (failed to decode)  com.highaltitudehacks.DVIAswiftv2com.flurry.analytics  (failed to decode)
2019-06-05 19:36:52 +0000  AlwaysThisDeviceOnly  None   Password  (failed to decode)  com.highaltitudehacks.DVIAswiftv2com.flurry.analytics  (failed to decode)
2019-06-05 19:44:50 +0000  WhenUnlocked          None   Password                      (failed to decode)                                     (failed to decode)
2019-06-06 05:23:05 +0000  WhenUnlocked          None   Password  keychainValue       com.highaltitudehacks.DVIAswiftv2                      (failed to decode)

```

**Environment (please complete the following information):**
 - Device: iPad4,8
 - OS: iOS 12.0
 - Frida Version 12.6.5
- Objection Version 1.6.4```

**Comment by leonjza** [comment] 2019-06-07 09:50
Thanks for the report! I have a local branch with a fix for this that I will push soon.

Going to close this as a duplicate of #230 though.

**Closed by leonjza** 2019-06-07 09:50 UTC
Labels: bug, duplicate

**Comment by commjoen** [comment] 2019-06-07 13:54
Thanks! Looking forward to it ;-)
