### ISSUE TITLE
An unexpected internal exception has occurred. If this looks like a code related error, please file a bug report!

### ISSUE THREAD

**Issue by zicohip** [sensepost/objection#596] opened 2022-12-22 00:38 UTC
```
...e.android. on (samsung: 7.1.2) [usb] # frida
An unexpected internal exception has occurred. If this looks like a code related error, please file a bug report!
'filename'

Python stack trace: Traceback (most recent call last):
  File "G:\python\Lib\site-packages\objection\console\repl.py", line 371, in start_repl
    self.run_command(document)
  File "G:\python\Lib\site-packages\objection\console\repl.py", line 185, in run_command
    exec_method(arguments)
  File "G:\python\Lib\site-packages\objection\commands\frida_commands.py", line 38, in frida_environment
    ('Script Filename', frida_env['filename']),
                        ~~~~~~~~~^^^^^^^^^^^^
KeyError: 'filename'
```

![image](https://user-images.githubusercontent.com/76248189/209029947-675ac7db-2824-4cff-9825-bf766aebb457.png)

**Comment by N0HagoNada** [comment] 2024-03-27 04:12
any updates here ?

**Comment by IPMegladon** [comment] 2024-07-13 11:55
Closing as duplicate of #535

**Closed by IPMegladon** 2024-07-13 11:55 UTC
Labels: freshissue
