### ISSUE TITLE
An unexpected internal exception has occurred. If this looks like a code related error, please file a bug report![bug] Bug Description Here

### ISSUE THREAD

**Issue by 0xSyam** [sensepost/objection#645] opened 2023-11-15 10:47 UTC
com.apps.MyXL on (POCO: 13) [usb] # frida
An unexpected internal exception has occurred. If this looks like a code related
 error, please file a bug report!
'filename'

Python stack trace: Traceback (most recent call last):
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages
\objection\console\repl.py", line 371, in start_repl
    self.run_command(document)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages
\objection\console\repl.py", line 185, in run_command
    exec_method(arguments)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages
\objection\commands\frida_commands.py", line 38, in frida_environment
    ('Script Filename', frida_env['filename']),
KeyError: 'filename'
![Capture](https://github.com/sensepost/objection/assets/65495612/3677b924-6bc8-42fb-8202-a27b574023eb)

**Comment by IPMegladon** [comment] 2024-07-10 15:55
If you could provide some more information on how to reproduce this it would be appreciated. Please also run with the debug flag '-d' to provide more verbose info.

**Comment by IPMegladon** [comment] 2024-07-13 11:56
Closing as duplicate of #535

**Closed by IPMegladon** 2024-07-13 11:56 UTC
Labels: freshissue
