### ISSUE TITLE
Getting Error while buliding the application after patching.

### ISSUE THREAD

**Issue by kushalx3** [sensepost/objection#245] opened 2019-06-24 04:54 UTC
```
Detected target device architecture as: arm64-v8a
Using latest Github gadget version: 12.6.8
Patcher will be using Gadget version: 12.6.8
Unpacking mnb.apk
App already has android.permission.INTERNET
Target class not specified, searching for launchable activity instead...
Unable to determine the launchable activity using aapt, trying to manually parse the AndroidManifest for activity aliases...
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/objection/console/cli.py", line 342, in patchapk
    patch_android_apk(**locals())
  File "/usr/local/lib/python3.6/dist-packages/objection/commands/mobile_packages.py", line 161, in patch_android_apk
    patcher.inject_load_library(target_class=target_class)
  File "/usr/local/lib/python3.6/dist-packages/objection/utils/patchers/android.py", line 708, in inject_load_library
    target_class if target_class else self._get_launchable_activity())
  File "/usr/local/lib/python3.6/dist-packages/objection/utils/patchers/android.py", line 294, in _get_launchable_activity
    manifest = self._get_android_manifest()
  File "/usr/local/lib/python3.6/dist-packages/objection/utils/patchers/android.py", line 239, in _get_android_manifest
    return ElementTree.parse(os.path.join(self.apk_temp_directory, 'AndroidManifest.xml'))
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
Cleaning up temp files...
Failed to cleanup with error: [Errno 2] No such file or directory: '/tmp/tmpmp35rnue.apktemp.objection.apk'
```

Any ideas for the root cause for this issue?
Using objection patchapk -s <apk> --skip-resources

**Comment by leonjza** [comment] 2019-06-24 15:11
Duplicate of #205. Since that issue I have added the ability to specify a target class for patching with the [`-t` flag](https://github.com/sensepost/objection/blob/master/objection/console/cli.py#L330).

**Closed by leonjza** 2019-06-24 15:11 UTC
Labels: apps, duplicate
