### ISSUE TITLE
frida.InvalidArgumentError: invalid PID

### ISSUE THREAD

**Issue by RonaldinhoL** [sensepost/objection#419] opened 2020-10-15 14:23 UTC
**Describe the bug**
when i use 
    objection -g com.topjohnwu.magisk explore -S "hooks.js"
it would exit with "frida.InvalidArgumentError: invalid PID"
it is always occur when i kill the app and new run the command.

**Evidence / Logs / Screenshots**
objection -g com.topjohnwu.magisk explore -S "xxx\hooks.js"
Using USB device `Pixel XL`
Agent injected and responds ok!
Importing and running startup script at: <_io.TextIOWrapper name='xxx\\hooks.js' mode='r' encoding='cp936'>
[-] Cronet pinner not found
Traceback (most recent call last):
  File "c:\users\ronaldinho\.pyenv\pyenv-win\versions\miniconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\ronaldinho\.pyenv\pyenv-win\versions\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ronaldinho\.pyenv\pyenv-win\versions\miniconda3\Scripts\objection.exe\__main__.py", line 7, in <module>
  File "c:\users\ronaldinho\.pyenv\pyenv-win\versions\miniconda3\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\ronaldinho\.pyenv\pyenv-win\versions\miniconda3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\ronaldinho\.pyenv\pyenv-win\versions\miniconda3\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\ronaldinho\.pyenv\pyenv-win\versions\miniconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\ronaldinho\.pyenv\pyenv-win\versions\miniconda3\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\ronaldinho\.pyenv\pyenv-win\versions\miniconda3\lib\site-packages\objection\console\cli.py", line 149, in explore
    response = agent.single(startup_script.read())
  File "c:\users\ronaldinho\.pyenv\pyenv-win\versions\miniconda3\lib\site-packages\objection\utils\agent.py", line 249, in single
    self.device.resume(self.spawned_pid)
  File "c:\users\ronaldinho\.pyenv\pyenv-win\versions\miniconda3\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "c:\users\ronaldinho\.pyenv\pyenv-win\versions\miniconda3\lib\site-packages\frida\core.py", line 148, in resume
    self._impl.resume(self._pid_of(target))
frida.InvalidArgumentError: invalid PID
Asking jobs to stop...
Unloading objection agent...

**Environment (please complete the following information):**
 - Device: [Pixel XL]
 - OS: [android 10]
 - Frida Version [12.11.18]
- Objection Version [1.9.6]

**Application**
app is magisk manager 7.5.1

**Additional context**
objection exit while the app is not, and runing normally, i try other app, also the same, objection exit.
i add a log before "agent.py, line 249", the PID is right, can be found in ps -A.
it there a bug in frida?

**Comment by leonjza** [comment] 2020-10-16 03:46
Dupe of #335

**Closed by leonjza** 2020-10-16 03:46 UTC
Labels: freshissue
