### ISSUE TITLE
Cannot download file from android local storage for non root phones

### ISSUE THREAD

**Issue by imdadvs** [sensepost/objection#146] opened 2018-10-09 12:30 UTC
The below error occurs when you try to download a file from android local storage "file download filename"

_An exception occurred while processing the command. If this looks like a code related error, please file a bug report!
Error: Error: VM::GetEnv failed: -2
    at e (frida/node_modules/frida-java/lib/result.js:7)
    at frida/node_modules/frida-java/lib/vm.js:71
    at a (frida/node_modules/frida-java/lib/class-factory.js:2764)
    at o (/_java.js:4570)
    at stringify (native)
    at frida/runtime/core.js:50
    at c (frida/runtime/message-dispatcher.js:71)
    at e (frida/runtime/message-dispatcher.js:55)
    at t (frida/runtime/message-dispatcher.js:25)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/objection/console/repl.py", line 389, in start_repl
    self.run_command(document)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/objection/console/repl.py", line 200, in run_command
    exec_method(arguments)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/objection/commands/filemanager.py", line 466, in download
    _download_android(source, destination)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/objection/commands/filemanager.py", line 591, in _download_android
    data = api.download()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/frida/core.py", line 319, in method
    return script._rpc_request('call', js_name, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/frida/core.py", line 247, in _rpc_request
    raise result[2]
frida.core.RPCException: Error: VM::GetEnv failed: -2
    at e (frida/node_modules/frida-java/lib/result.js:7)
    at frida/node_modules/frida-java/lib/vm.js:71
    at a (frida/node_modules/frida-java/lib/class-factory.js:2764)
    at o (/_java.js:4570)
    at stringify (native)
    at frida/runtime/core.js:50
    at c (frida/runtime/message-dispatcher.js:71)
    at e (frida/runtime/message-dispatcher.js:55)
    at t (frida/runtime/message-dispatcher.js:25)_

**Comment by leonjza** [comment] 2018-10-09 13:35
Duplicate of #92

**Closed by leonjza** 2018-10-09 13:35 UTC
