### ISSUE TITLE
SSL Pinning hooks not effective

### ISSUE THREAD

**Issue by gregkuhnert** [sensepost/objection#35] opened 2017-10-17 20:15 UTC
Hi Objection team.

I am part of a team that is reverse engineering the DJI GO 4 IOS application. As part of that effort, we wanted to peek inside SSL traffic. Objection looked to fit our needs. However, your SSL pinning hooks were not effective for a device running iOS 10.x

After searching, we used hooks found which we found were able to disable all SSL pinning for iOS 10.x at https://raw.githubusercontent.com/vtky/Swizzler2/master/SSLKillSwitch.js

Would appreciate if you could review your hooks and update accordingly.

Our progress and methods are documented at https://dji.retroroms.info/ if you would like to replicate/test to help you validate our results.

**Comment by leonjza** [comment] 2017-10-17 20:24
Hey!

Thanks for reaching out about this! 

> After searching, we used hooks found which we found were able to disable all SSL pinning for iOS 10.x at https://raw.githubusercontent.com/vtky/Swizzler2/master/SSLKillSwitch.js

This link is great thank you!

Just to double check, are you referring to this application? https://itunes.apple.com/us/app/dji-go-4/id1170452592?mt=8. I'll test this and check what is needed to make the pinning bypass work out of the box.

**Comment by leonjza** [comment] 2017-10-18 09:58
I did some digging on this.

First, apart from the few framework specific hooks in the linked `SSLKillSwitch.js` file, this collection of hooks seem to also be Frida implementations of the SSLKillSwitch2 project (which is what the hooks objection uses are also based on). I am actually unsure what could have caused that to work and not those that is in objection already. (more on that in a bit*).

Inspecting the application in questions' behaviour, I could see a number of clear text HTTP API requests being made where pinning is obviously not a problem. Of the few HTTPS requests that **are** made, none appear to be pinning the remote certificate and seem to be quite happy with my vanilla proxy setup (using Burpsuite). 
Based on section [9.2](https://dji.retroroms.info/howto/iosfrida) of your wiki article, you make mention of the fact that requests to a specific hostname failed. So, I dug a little deeper to try and find out how requests to this URL is handled. An instance of the `DJILogEvent` class is initialised and set up. Once the request is made, `[DJILogEvent sendCommonData]` is called, which in turn calls `[ASIHTTPRequest requestWithURL:r24];` and dispatches it as an asynchronous request.

As far as making requests with `ASIHTTPRequest` go, the only thing I could find was the fact that it validates the legitimacy of the servers certificate and was not configured to pin anything (that I could find quickly anyways).

I double checked my setup to see why I was able to see the requests sent to the hostname in question and realised that it may be related to the fact that I trust my proxies CA certificate. Removed the CA certificate and finally was experiencing the same behaviour as you reported.

(the more bit*) Could you double check that your mobile device trusts your intercepting proxies CA certificate? I have a feeling that this is the only validation that is done for the application in question for HTTPS requests.

Let me know!

**Comment by leonjza** [comment] 2017-10-22 17:20
Spent most of the afternoon debugging this a bit more after I got more information from @gregkuhnert via IRC.

Turns out, the hook to `tls_helper_create_peer_trust` breaks TLS connections in some odd cases (like this.) So, for now I have added a flag (`--ignore-ios10-tls-helper`) in the following commit:
8fba5d3ca

**Comment by leonjza** [comment] 2017-10-23 15:46
In closing, according to @gregkuhnert and their testing they were able to successfully bypass the pinning in their target application with the following hook:

```javascript
var AFSecurityPolicy = ObjC.classes.AFSecurityPolicy;
var setSSLPinningMode = AFSecurityPolicy['- setSSLPinningMode:'];
var setSSLPinningModeImpl = setSSLPinningMode.implementation;

setSSLPinningMode.implementation = ObjC.implement(setSSLPinningMode, function (handle, selector, originalResult) {

  setSSLPinningModeImpl(handle, selector, 0);
  console.log('AFSecurityPolicy:setSSLPinningMode. Changing from: ', originalResult, 'to: 1');
  });
```

From my side, testing has unfortunately been inconclusive, but, I am leaving this here in case someone else comes across a similar scenario and can help with reproducible steps.

**Closed by leonjza** 2017-10-23 15:46 UTC
Labels: enhancement
