### ISSUE TITLE
objection run issue 

### ISSUE THREAD

**Issue by naveen12** [sensepost/objection#39] opened 2017-11-09 13:06 UTC
installed objection tools on mac by "pip3 install -U objection"

while accessing the tool "objection --help"  it showing some error message as below python 3.6 was installed

(virtual-python3) ymac:objection apple$ objection --help

***
Failed to load the Frida native extension: dlopen(/Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so, 2): Symbol not found: ___strlcpy_chk
  Referenced from: /Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "/Users/apple/virtual-python3/bin/objection", line 7, in <module>
    from objection.console.cli import cli
  File "/Users/apple/virtual-python3/lib/python3.6/site-packages/objection/console/cli.py", line 2, in <module>
    import frida
  File "/Users/apple/virtual-python3/lib/python3.6/site-packages/frida/__init__.py", line 26, in <module>
    raise ex
  File "/Users/apple/virtual-python3/lib/python3.6/site-packages/frida/__init__.py", line 6, in <module>
    import _frida
ImportError: dlopen(/Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so, 2): Symbol not found: ___strlcpy_chk
  Referenced from: /Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so

**Comment by leonjza** [comment] 2017-11-09 18:56
I think this relates to the problem in #38. Can you try to just install `frida` with `pip3 install -U frida`?

**Comment by naveen12** [comment] 2017-11-13 11:31
i did and later ran pip3 install -U objection 
and faced below issues
(virtual-python3) ymac:Documents apple$ pip3 install -U frida
Requirement already up-to-date: frida in /Users/apple/virtual-python3/lib/python3.6/site-packages
Requirement already up-to-date: prompt-toolkit>=0.57 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from frida)
Requirement already up-to-date: colorama>=0.2.7 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from frida)
Requirement already up-to-date: pygments>=2.0.2 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from frida)
Requirement already up-to-date: six>=1.9.0 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from prompt-toolkit>=0.57->frida)
Requirement already up-to-date: wcwidth in /Users/apple/virtual-python3/lib/python3.6/site-packages (from prompt-toolkit>=0.57->frida)
(virtual-python3) ymac:Documents apple$ pip3 install -U objection
Requirement already up-to-date: objection in /Users/apple/virtual-python3/lib/python3.6/site-packages
Requirement already up-to-date: jinja2 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from objection)
Requirement already up-to-date: tabulate in /Users/apple/virtual-python3/lib/python3.6/site-packages (from objection)
Requirement already up-to-date: requests in /Users/apple/virtual-python3/lib/python3.6/site-packages (from objection)
Requirement already up-to-date: delegator.py in /Users/apple/virtual-python3/lib/python3.6/site-packages (from objection)
Requirement already up-to-date: prompt-toolkit in /Users/apple/virtual-python3/lib/python3.6/site-packages (from objection)
Requirement already up-to-date: frida in /Users/apple/virtual-python3/lib/python3.6/site-packages (from objection)
Requirement already up-to-date: jsbeautifier in /Users/apple/virtual-python3/lib/python3.6/site-packages (from objection)
Requirement already up-to-date: click in /Users/apple/virtual-python3/lib/python3.6/site-packages (from objection)
Requirement already up-to-date: MarkupSafe>=0.23 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from jinja2->objection)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from requests->objection)
Requirement already up-to-date: idna<2.7,>=2.5 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from requests->objection)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from requests->objection)
Requirement already up-to-date: certifi>=2017.4.17 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from requests->objection)
Collecting pexpect>=4.1.0 (from delegator.py->objection)
  Using cached pexpect-4.3.0-py2.py3-none-any.whl
Requirement already up-to-date: six>=1.9.0 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from prompt-toolkit->objection)
Requirement already up-to-date: wcwidth in /Users/apple/virtual-python3/lib/python3.6/site-packages (from prompt-toolkit->objection)
Requirement already up-to-date: pygments>=2.0.2 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from frida->objection)
Requirement already up-to-date: colorama>=0.2.7 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from frida->objection)
Requirement already up-to-date: editorconfig>=0.12.0 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from jsbeautifier->objection)
Requirement already up-to-date: ptyprocess>=0.5 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from pexpect>=4.1.0->delegator.py->objection)
Installing collected packages: pexpect
  Found existing installation: pexpect 4.2.1
    Uninstalling pexpect-4.2.1:
Exception:
Traceback (most recent call last):
  File "/Users/apple/virtual-python3/lib/python3.6/shutil.py", line 544, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/Users/apple/virtual-python3/lib/python3.6/site-packages/pexpect-4.2.1.dist-info/DESCRIPTION.rst' -> '/var/folders/z8/vxvtd5yj0ls68c72cgyn3pr00000gn/T/pip-hu3x6sbu-uninstall/Users/apple/virtual-python3/lib/python3.6/site-packages/pexpect-4.2.1.dist-info/DESCRIPTION.rst'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apple/virtual-python3/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/apple/virtual-python3/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Users/apple/virtual-python3/lib/python3.6/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Users/apple/virtual-python3/lib/python3.6/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Users/apple/virtual-python3/lib/python3.6/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Users/apple/virtual-python3/lib/python3.6/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/Users/apple/virtual-python3/lib/python3.6/shutil.py", line 559, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/Users/apple/virtual-python3/lib/python3.6/site-packages/pexpect-4.2.1.dist-info/DESCRIPTION.rst'

**Comment by naveen12** [comment] 2017-11-13 11:34
(virtual-python3) ymac:Documents apple$ objection

***
Failed to load the Frida native extension: dlopen(/Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so, 2): Symbol not found: ___strlcpy_chk
  Referenced from: /Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "/Users/apple/virtual-python3/bin/objection", line 7, in <module>
    from objection.console.cli import cli
  File "/Users/apple/virtual-python3/lib/python3.6/site-packages/objection/console/cli.py", line 2, in <module>
    import frida
  File "/Users/apple/virtual-python3/lib/python3.6/site-packages/frida/__init__.py", line 26, in <module>
    raise ex
  File "/Users/apple/virtual-python3/lib/python3.6/site-packages/frida/__init__.py", line 6, in <module>
    import _frida
ImportError: dlopen(/Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so, 2): Symbol not found: ___strlcpy_chk
  Referenced from: /Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so

**Comment by leonjza** [comment] 2017-11-13 11:37
For some reason, the user you are running the install command as does not have the required privileges to write to the `/Users/apple/virtual-python3` directory as indicated on the last line of the stack trace.

Could I suggest you remove the `/Users/apple/virtual-python3/` directory completely and just give a [fresh install](https://github.com/sensepost/objection/wiki/Installation#virtual-installation) a try again and report the output of the entire session? Maybe with the following commands:

* `id`
* `rm -Rf /Users/apple/virtual-python3/`
* `virtualenv --python=python3 ~/virtual-python3`
* `source ~/virtual-python3/bin/activate`
* `python -V`
*  `pip3 install -U objection`

Let me know!

**Comment by naveen12** [comment] 2017-11-14 15:20
fallowed the same steps as you mentioned and objection run time faced issue, please find the total log below

ymac:~ apple$ ls
08-23-2017
25 AUG
Applications
DCIns_ShfShortcut_NueMD_144
Desktop
Documents
Downloads
Library
Movies
Music
Pictures
Public
Spark
frida-10.6.21-py3.6-macosx-10.6-intel.egg
libirecovery
nuesoft
nuesoft_DC_NCRM
nuesoft_LastXpressJNLP STagHFCase
userdic.tlx
virtual-python
virtual-python3
ymac:~ apple$ python -V
Python 2.7.2
ymac:~ apple$ rm -rf /User
User Guides And Information/ Users/
ymac:~ apple$ python -V
Python 2.7.2
ymac:~ apple$ virtualenv --python=python3 ~/virtual-python3
Running virtualenv with interpreter /Library/Frameworks/Python.framework/Versions/3.6/bin/python3
Using base prefix '/Library/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/apple/virtual-python3/bin/python3
Also creating executable in /Users/apple/virtual-python3/bin/python
Installing setuptools, pip, wheel...done.
ymac:~ apple$ source ~/virtual-python3/bin/activate
(virtual-python3) ymac:~ apple$ python -V
Python 3.6.3
(virtual-python3) ymac:~ apple$ pip3 install -U objection
Collecting objection
Collecting jsbeautifier (from objection)
Collecting requests (from objection)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting tabulate (from objection)
Collecting prompt-toolkit (from objection)
  Using cached prompt_toolkit-1.0.15-py3-none-any.whl
Collecting click (from objection)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting delegator.py (from objection)
Collecting frida (from objection)
Collecting jinja2 (from objection)
  Using cached Jinja2-2.10-py2.py3-none-any.whl
Collecting six>=1.6.1 (from jsbeautifier->objection)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting editorconfig>=0.12.0 (from jsbeautifier->objection)
  Using cached EditorConfig-0.12.1-py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->objection)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->objection)
  Using cached certifi-2017.11.5-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests->objection)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests->objection)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit->objection)
  Using cached wcwidth-0.1.7-py2.py3-none-any.whl
Collecting pexpect>=4.1.0 (from delegator.py->objection)
  Using cached pexpect-4.3.0-py2.py3-none-any.whl
Collecting colorama>=0.2.7 (from frida->objection)
  Using cached colorama-0.3.9-py2.py3-none-any.whl
Collecting pygments>=2.0.2 (from frida->objection)
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from jinja2->objection)
Collecting ptyprocess>=0.5 (from pexpect>=4.1.0->delegator.py->objection)
  Using cached ptyprocess-0.5.2-py2.py3-none-any.whl
Installing collected packages: six, editorconfig, jsbeautifier, chardet, certifi, idna, urllib3, requests, tabulate, wcwidth, prompt-toolkit, click, ptyprocess, pexpect, delegator.py, colorama, pygments, frida, MarkupSafe, jinja2, objection
Successfully installed MarkupSafe-1.0 certifi-2017.11.5 chardet-3.0.4 click-6.7 colorama-0.3.9 delegator.py-0.0.13 editorconfig-0.12.1 frida-10.6.21 idna-2.6 jinja2-2.10 jsbeautifier-1.7.4 objection-1.2.2 pexpect-4.3.0 prompt-toolkit-1.0.15 ptyprocess-0.5.2 pygments-2.2.0 requests-2.18.4 six-1.11.0 tabulate-0.8.1 urllib3-1.22 wcwidth-0.1.7
(virtual-python3) ymac:~ apple$ objection

***
Failed to load the Frida native extension: dlopen(/Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so, 2): Symbol not found: ___strlcpy_chk
  Referenced from: /Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "/Users/apple/virtual-python3/bin/objection", line 7, in <module>
    from objection.console.cli import cli
  File "/Users/apple/virtual-python3/lib/python3.6/site-packages/objection/console/cli.py", line 2, in <module>
    import frida
  File "/Users/apple/virtual-python3/lib/python3.6/site-packages/frida/__init__.py", line 26, in <module>
    raise ex
  File "/Users/apple/virtual-python3/lib/python3.6/site-packages/frida/__init__.py", line 6, in <module>
    import _frida
ImportError: dlopen(/Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so, 2): Symbol not found: ___strlcpy_chk
  Referenced from: /Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so
(virtual-python3) ymac:~ apple$

**Comment by naveen12** [comment] 2017-11-14 15:26
please help me, i need to complete the project before this friday

**Comment by naveen12** [comment] 2017-11-14 15:31
even checking the frida version also facing same issue
(virtual-python3) ymac:~ apple$ frida --version

***
Failed to load the Frida native extension: dlopen(/Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so, 2): Symbol not found: ___strlcpy_chk
  Referenced from: /Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "/Users/apple/virtual-python3/bin/frida", line 7, in <module>
    from frida.repl import main
  File "/Users/apple/virtual-python3/lib/python3.6/site-packages/frida/__init__.py", line 26, in <module>
    raise ex
  File "/Users/apple/virtual-python3/lib/python3.6/site-packages/frida/__init__.py", line 6, in <module>
    import _frida
ImportError: dlopen(/Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so, 2): Symbol not found: ___strlcpy_chk
  Referenced from: /Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so

**Comment by naveen12** [comment] 2017-11-14 15:45
i have removed python 3.6.6 and installed python 3.6
still the issue is same

**Comment by leonjza** [comment] 2017-11-14 15:55
Heya,

From the console output, it looks like you did not follow the commands exactly as I have suggested, and miss-typed the `rm` command that should have removed the old python3 virtual environment. As a result, running the installation command had cached packages installed instead of freshly downloaded ones.

**Comment by naveen12** [comment] 2017-11-15 08:16
sorry for the last process i removed folder manually on that time
now i fallowed your instructions and the result is same
ymac:~ apple$ id
uid=501(apple) gid=20(staff) groups=20(staff),401(com.apple.access_screensharing),12(everyone),33(_appstore),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),100(_lpoperator),204(_developer)
ymac:~ apple$ rm -Rf /Users/apple/virtual-python3/
ymac:~ apple$ ls
08-23-2017
25 AUG
Applications
DCIns_ShfShortcut_NueMD_144
Desktop
Documents
Downloads
Library
Movies
Music
Pictures
Public
Spark
frida-10.6.21-py3.6-macosx-10.6-intel.egg
libirecovery
nuesoft
nuesoft_DC_NCRM
nuesoft_LastXpressJNLP STagHFCase
userdic.tlx
virtual-python
ymac:~ apple$ virtualenv --python=python3 ~/virtual-python3
Running virtualenv with interpreter /Library/Frameworks/Python.framework/Versions/3.6/bin/python3
Using base prefix '/Library/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/apple/virtual-python3/bin/python3
Also creating executable in /Users/apple/virtual-python3/bin/python
Installing setuptools, pip, wheel...done.
ymac:~ apple$ source ~/virtual-python3/bin/activate
(virtual-python3) ymac:~ apple$ python -V
Python 3.6.0
(virtual-python3) ymac:~ apple$ pip3 install -U objection
Collecting objection
Collecting delegator.py (from objection)
Collecting jinja2 (from objection)
  Using cached Jinja2-2.10-py2.py3-none-any.whl
Collecting jsbeautifier (from objection)
Collecting requests (from objection)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting tabulate (from objection)
Collecting frida (from objection)
Collecting click (from objection)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting prompt-toolkit (from objection)
  Using cached prompt_toolkit-1.0.15-py3-none-any.whl
Collecting pexpect>=4.1.0 (from delegator.py->objection)
  Using cached pexpect-4.3.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from jinja2->objection)
Collecting editorconfig>=0.12.0 (from jsbeautifier->objection)
  Using cached EditorConfig-0.12.1-py3-none-any.whl
Collecting six>=1.6.1 (from jsbeautifier->objection)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->objection)
  Using cached certifi-2017.11.5-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->objection)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests->objection)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests->objection)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting colorama>=0.2.7 (from frida->objection)
  Using cached colorama-0.3.9-py2.py3-none-any.whl
Collecting pygments>=2.0.2 (from frida->objection)
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit->objection)
  Using cached wcwidth-0.1.7-py2.py3-none-any.whl
Collecting ptyprocess>=0.5 (from pexpect>=4.1.0->delegator.py->objection)
  Using cached ptyprocess-0.5.2-py2.py3-none-any.whl
Installing collected packages: ptyprocess, pexpect, delegator.py, MarkupSafe, jinja2, editorconfig, six, jsbeautifier, certifi, chardet, urllib3, idna, requests, tabulate, wcwidth, prompt-toolkit, colorama, pygments, frida, click, objection
Successfully installed MarkupSafe-1.0 certifi-2017.11.5 chardet-3.0.4 click-6.7 colorama-0.3.9 delegator.py-0.0.13 editorconfig-0.12.1 frida-10.6.21 idna-2.6 jinja2-2.10 jsbeautifier-1.7.4 objection-1.2.2 pexpect-4.3.0 prompt-toolkit-1.0.15 ptyprocess-0.5.2 pygments-2.2.0 requests-2.18.4 six-1.11.0 tabulate-0.8.1 urllib3-1.22 wcwidth-0.1.7
(virtual-python3) ymac:~ apple$ objection

***
Failed to load the Frida native extension: dlopen(/Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so, 2): Symbol not found: ___strlcpy_chk
  Referenced from: /Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "/Users/apple/virtual-python3/bin/objection", line 7, in <module>
    from objection.console.cli import cli
  File "/Users/apple/virtual-python3/lib/python3.6/site-packages/objection/console/cli.py", line 2, in <module>
    import frida
  File "/Users/apple/virtual-python3/lib/python3.6/site-packages/frida/__init__.py", line 26, in <module>
    raise ex
  File "/Users/apple/virtual-python3/lib/python3.6/site-packages/frida/__init__.py", line 6, in <module>
    import _frida
ImportError: dlopen(/Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so, 2): Symbol not found: ___strlcpy_chk
  Referenced from: /Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/apple/virtual-python3/lib/python3.6/site-packages/_frida.cpython-36m-darwin.so
(virtual-python3) ymac:~ apple$

**Comment by leonjza** [comment] 2017-11-21 07:06
What is unclear to me is why you are getting cached packages for installation in a new virtual environment. Nonetheless, for the installation command, can you try `pip3 --no-cache-dir install objection`.

**Comment by leonjza** [comment] 2017-12-11 11:21
Hey @naveen12 did you manage to try the installation with the command I suggested?

**Comment by leonjza** [comment] 2018-01-10 10:52
Closing this for now. Feel free to reopen once there is more information.

**Closed by leonjza** 2018-01-10 10:52 UTC
Labels: help wanted

**Comment by encryptedsin** [comment] 2019-02-05 10:48
I am having a similar issue with objection.
Specs:
Python 3.7.2 and Python 2.7.13 installed.
Frida 12.3.1 installed along with frida-tools.

The below exception is thrown when i attempt to run objection (even in powershell):
PS C:\Users\JYOTIS> objection
Traceback (most recent call last):
  File "c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (prompt-toolkit 2.0.8 (c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages), Requirement.parse('prompt_toolkit<2.0.0,>=1.0.15'), {'objection'})

During handling of the above exception, another exception occurred:
PS C:\Users\{USER}> objection
Traceback (most recent call last):
  File "C:\Users\JYOTIS\AppData\Local\Programs\Python\Python37-32\Scripts\objection-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 3126, in <module>
    @_call_aside
  File "c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'prompt_toolkit<2.0.0,>=1.0.15' distribution was not found and is required by objection.

If I uninstall objection, frida-ps too throws the exception caused by missing prompt_toolkit<2.0.0,>=1.0.15.

Below is fro extra reference:
PS C:\Users\JYOTIS> pip3 install prompt_toolkit
Requirement already satisfied: prompt_toolkit in c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages (2.0.8)
Requirement already satisfied: six>=1.9.0 in c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages (from prompt_toolkit) (1.12.0)
Requirement already satisfied: wcwidth in c:\users\jyotis\appdata\local\programs\python\python37-32\lib\site-packages (from prompt_toolkit) (0.1.7)

Kindly assist.

**Comment by Josue198s** [comment] 2020-03-25 13:34
I have the same problem.
When I run objection explore on mac osx  I get the same error. 

sh-3.2# frida --version
12.8.1
sh-3.2# objection version
objection: 1.8.3


sh-3.2# objection explore
Using USB device `iPhone`
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/objection", line 11, in <module>
    load_entry_point('objection==1.8.3', 'console_scripts', 'objection')()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/objection/console/cli.py", line 114, in explore
    agent.inject()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/objection/utils/agent.py", line 202, in inject
    session = self.get_session()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/objection/utils/agent.py", line 166, in get_session
    self.spawned_pid = self.device.spawn(state_connection.gadget_name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/frida-12.8.1-py3.8-macosx-10.9-x86_64.egg/frida/core.py", line 26, in wrapper
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/frida-12.8.1-py3.8-macosx-10.9-x86_64.egg/frida/core.py", line 140, in spawn
frida.InvalidArgumentError: unable to find app with bundle identifier “Gadget”
Exception ignored in: <function Pool.__del__ at 0x10d1b4670>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
    self._change_notifier.put(None)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
